const tap = require('tap')
const index = require('../index')
const type = require('../lib/type')
const Operation = require('../lib/Action')
const Iterator = require('../lib/Iterator')
const Delta = require('../lib/Delta')

tap.equal(index.type, type)
tap.equal(index.Operation, Operation)
tap.equal(index.Iterator, Iterator)
tap.equal(index.Delta, Delta)
