language: node_js
node_js:
    - "8"
cache:
    directories:
        - "node_modules"
script: "npm run test:cover"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
